# Generated by Django 2.2.16 on 2022-11-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221114_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', 'text'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
