# Generated by Django 2.2.16 on 2022-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221116_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите сообщение', verbose_name='Текст'),
        ),
    ]
