# Generated by Django 2.2.16 on 2022-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20221123_2016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name="%(model_name)s's %(field_labels)s are not unique.",
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='users already followed'),
        ),
    ]
